// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegicideAction } from "./RegicideAction";

export type ClientMsg = { "Join": { lobby: string | null, client_token: string, } } | { "Action": { action: RegicideAction, } };
