// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegicideAction = "Init" | { "Play": { cards: Array<number>, } } | { "Discard": { cards: Array<number>, } } | { "Jester": { player: string, } };
