// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsCard } from "./JsCard";
import type { Phase } from "./Phase";

export type ServerMsg = { "Join": { joined: string, } } | { "Game": { phase: Phase, players: Array<[string, number]>, library_size: number, discard_size: number, damage: number, enemy: JsCard, hand: Array<JsCard>, resolving: Array<Array<JsCard>>, } } | "Victory" | "Defeat";
