// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { Phase } from "./Phase";

export type ServerMsg = { "Join": { lobbies: Array<string>, joined: string | null, } } | { "State": { phase: Phase, players: { [key in string]?: number }, library_size: number, discard_size: number, damage: number, hand: Array<Card>, resolving: Array<Array<Card>>, } };
